name: pr voter

on: [pull_request]

jobs:
  pr-voter:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    - name: Run test
      run: dub test
